/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.PatientRole;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestVitalsWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ruchi
 */
public class ViewResultsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TestVitalsWorkRequest request;
    private UserAccount userAccount;

    /**
     * Creates new form ViewResultsJPanel
     */
    public ViewResultsJPanel(JPanel upc, UserAccount uaa, TestVitalsWorkRequest r) {
        initComponents();
        this.userProcessContainer = upc;
        this.request = r;
        this.userAccount = uaa;
        txtPatientName.setText(request.getPatientSender().getEmployee().getName());
        /**
         * if(request.getReceptionistSender().getEmployee().getName()==null) {
         * txtReceptionist.setText(""); } else
         * txtReceptionist.setText(request.getReceptionistSender().getEmployee().getName());
         *
         * //
         * txtReciever.setText(request.getReceiver().getEmployee().getName());
         */
        txtRequestDate.setText(String.valueOf(request.getRequestDate()));
        txtStatus.setText(request.getStatus());
        txtMessageSent.setText(request.getMessage());
        txtResults.setText(request.getTestResult());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRequestDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMessageSent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Patient Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 165, -1, -1));

        txtPatientName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 460, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Request Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 220, -1, -1));

        txtRequestDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtRequestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 460, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Message Sent:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        txtMessageSent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtMessageSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageSentActionPerformed(evt);
            }
        });
        add(txtMessageSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 460, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Results:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        txtResults.setColumns(20);
        txtResults.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtResults.setRows(5);
        jScrollPane1.setViewportView(txtResults);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 590, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 460, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("<< BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 900, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("VIEW REQUEST");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\Project\\src\\userInterface\\Alien Ink 2560X1600 Abstract Background.jpg")); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2090, 1260));

        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1710, 1130));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageSentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageSentActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMessageSent;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtRequestDate;
    private javax.swing.JTextArea txtResults;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
