/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.DeliveryRole;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestVitalsWorkRequest;

import java.awt.CardLayout;
import java.awt.Component;

import java.text.MessageFormat;
import javax.swing.JPanel;
import javax.swing.text.Document;
import java.text.*;
import java.awt.print.*;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import com.textmagic.sms.TextMagicMessageService;
import com.textmagic.sms.dto.SentMessage;
import com.textmagic.sms.exception.ServiceException;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author ruchi
 */
public class ProcessingDeliveryJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private TestVitalsWorkRequest request;
    private UserAccount userAccount;
    private Enterprise enterprise;

    /**
     * Creates new form ProcessingDeliveryJPanel
     */
    public ProcessingDeliveryJPanel(JPanel upc, UserAccount ua, Enterprise e, TestVitalsWorkRequest r) {
        initComponents();
        this.userProcessContainer = upc;
        this.request = r;
        this.enterprise = e;
        this.userAccount = ua;
        jTextField1.setText(request.getPatientSender().getEmployee().getName());
        jTextField2.setText(request.getPatientSender().getEmployee().getAddress());
        jTextField3.setText(request.getPatientSender().getEmployee().getContactNo());
        jTextField4.setText(request.getDeliveryBoy().getEmployee().getName());
        jTextField5.setText(request.getOrderId());
        jTextField6.setText(String.valueOf(request.getTotAmount()));
        jTextArea1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        mail = new javax.swing.JButton();
        sendSMS = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("PATIENT:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("ADDRESS:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("CONTACT NO:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("DELIVERY PERSON:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\AED\\images\\stock-photo-medical-delivery-glyph-icon-style-is-bicolor-flat-symbol-blue-and-white-colors-rounded-angles-320882927.jpg")); // NOI18N
        jButton1.setText("LEAVE TO DELIVER MEDICINES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 840, 350, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("ORDER ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 320, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 320, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 320, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 320, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 320, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PROCESSING THE DELIVERY ORDER");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("TOTAL AMOUNT:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 320, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\AED\\images\\print-button.png")); // NOI18N
        jButton2.setText("TAKE A PRINT OF THE ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 350, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\AED\\images\\images.jpg")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 930, 120, 50));

        mail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mail.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\AED\\images\\icon-ios7-email-128.png")); // NOI18N
        mail.setText("SEND A MAIL TO THE PATIENT");
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 350, -1));

        sendSMS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sendSMS.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\AED\\images\\stock-photo-phone-sms-glyph-icon-style-is-bicolor-flat-symbol-yellow-and-white-colors-rounded-angles-blue-337151111.jpg")); // NOI18N
        sendSMS.setText("SEND SMS TO THE PATIENT");
        sendSMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendSMSActionPerformed(evt);
            }
        });
        add(sendSMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 740, 350, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\Final Project\\Project\\src\\userInterface\\Alien Ink 2560X1600 Abstract Background.jpg")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -50, 1810, 1510));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 802, 28, 17));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /**
         * PrinterJob job = PrinterJob.getPrinterJob();
         * job.setJobName("ProcessingDeliveryJPanel");
         *
         * job.setPrintable (new Printable() { public int print(Graphics pg,
         * PageFormat pf, int pageNum){ if (pageNum > 0){ return
         * Printable.NO_SUCH_PAGE; }
         *
         * Graphics2D g2 = (Graphics2D) pg; g2.translate(pf.getImageableX(),
         * pf.getImageableY()); ProcessingDeliveryJPanel.print(g2); return
         * Printable.PAGE_EXISTS; } }); boolean ok = job.printDialog(); if (ok)
         * { try { job.print(); } catch (PrinterException ex) {
         *
         * }
         */
        MessageFormat header = new MessageFormat("Order Details");

        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            String a = jTextField1.getText();
            String b = jTextField2.getText();
            String c = jTextField3.getText();
            String d = jTextField4.getText();
            String e = jTextField5.getText();
            String f = jTextField6.getText();
            String comp = ("Patient Name: " + a + "\n" + "Patient Address: " + b + "\n" + "Patient's Contact No: " + c + "\n" + "Delivery Person's Name: " + d + "\n"
                    + "Order ID: " + e + "\n" + "Total Amount: " + f + "\n");
            jTextArea1.setText(comp);
            jTextArea1.print(header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("cannot print", e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        request.setStatus("Left to Deliver the medicines");
        JOptionPane.showMessageDialog(null, "You can now leave to deliver the medicines");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DeliveryWorkAreaJPanel deliver = (DeliveryWorkAreaJPanel) component;
        deliver.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // String to =request.getPatientSender().getEmployee().geteMailId();
        String to = "gupta.ruchi19011991@gmail.com";
        String from = "gupta.r1901@gmail.com";
        String host = "smtp.gmail.com";
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication("gupta.r1901@gmail.com", "Sweethome@01472");
            }
        }
        );
        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject("Order Status");
            message.setText("Your Order has been dispached and you will recieve medicines iin few hours");
            javax.mail.Transport.send(message);
            JOptionPane.showMessageDialog(null, "message sent to " + request.getPatientSender().getEmployee().getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mailActionPerformed

    private void sendSMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendSMSActionPerformed
        String text = "Person has left to deliver";
        String dummyNumber = request.getPatientSender().getEmployee().getContactNo();
        TextMagicMessageService service = new TextMagicMessageService("pragyam", "Neu@2015");
        try {
            SentMessage message = service.send(text, dummyNumber);
            JOptionPane.showMessageDialog(null, "Message has been sent successfuully");
        } catch (ServiceException ex) {

            JOptionPane.showMessageDialog(null, "Cant send message. Reason: " + ex.getMessage());
        }
    }//GEN-LAST:event_sendSMSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton mail;
    private javax.swing.JButton sendSMS;
    // End of variables declaration//GEN-END:variables
}
