/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ReceptionistRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import business.Validation.MyEmailVerifier;
import business.Validation.MyNumericVerifier;
import business.Validation.MyPhoneNumer;
import business.Validation.MyStringVerifier;
import business.Validation.MyaddressVerifier;
import business.Validation.NotEmptyVerifier;
import com.googlecode.javacv.CanvasFrame;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core;
import com.googlecode.javacv.cpp.opencv_highgui;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ruchi
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ReceptionistOrganization rOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization pOrganization;
    private ArrayList<String> gen;
    private int i = 1;
    private String emp = "";
    private ArrayList<Employee> empArry;

    /**
     * Creates new form CreatePatientJPanel
     */
    public CreatePatientJPanel(JPanel upc, UserAccount ua, ReceptionistOrganization o, Enterprise e) {
        initComponents();
        this.gen = new ArrayList<>();
        this.empArry = new ArrayList<>();
        this.userProcessContainer = upc;
        this.rOrganization = o;
        this.enterprise = e;
        this.userAccount = ua;
        MyStringVerifier iv = new MyStringVerifier();
        nameJTextField.setInputVerifier(iv);
        MyaddressVerifier nev = new MyaddressVerifier();
        txtAddress.setInputVerifier(nev);
        MyEmailVerifier nv = new MyEmailVerifier();
        txtemailId.setInputVerifier(nv);
        MyPhoneNumer contact = new MyPhoneNumer();
        txtContactNumber.setInputVerifier(contact);
        NotEmptyVerifier dob = new NotEmptyVerifier();
        dobChooser.setInputVerifier(dob);
        gen.add(new String("MALE"));
        gen.add(new String("FEMALE"));
        gen.add(new String("OTHERS"));
        comboBoxGender.removeAllItems();
        for (String g : gen) {
            comboBoxGender.addItem(g);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtemailId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dobChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        comboBoxGender = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ENTER PATIENT DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 85, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 167, -1, -1));

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 157, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 217, -1, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 217, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Email id:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 267, -1, -1));

        txtemailId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtemailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 267, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Contact Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 317, -1, -1));

        txtContactNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 317, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Date Of Birth:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 372, -1, -1));
        add(dobChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 372, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Gender:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        comboBoxGender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGenderActionPerformed(evt);
            }
        });
        add(comboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 180, -1));

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        submitJButton.setText("Register");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setText("<< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 760, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Start the webcam to capture a photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 290, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Capture a photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 290, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\Final Project\\Project\\src\\userInterface\\Alien Ink 2560X1600 Abstract Background.jpg")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1900, 1090));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxGenderActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed

        String name = nameJTextField.getText();

        String address = txtAddress.getText();
        String emailId = txtemailId.getText();
        String contactNo = txtContactNumber.getText();
        Date d2 = dobChooser.getDate();
        String gend = (String) comboBoxGender.getSelectedItem();
        if (dobChooser.getDate() == null||name.isEmpty()||address.isEmpty()||emailId.isEmpty()||contactNo.isEmpty()||gend.isEmpty()) {
            if(name.isEmpty()||address.isEmpty()||emailId.isEmpty()||contactNo.isEmpty()||gend.isEmpty())
            {
              JOptionPane.showMessageDialog(null, "you cannot leave any field empty");   
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please select a date first");
            }
            
        } else {
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (o.getName().equals("Patient Organization")) {
                    o.getEmployeeDirectory().createEmployee(name, address, emailId, contactNo, d2, gend);
                    nameJTextField.setText("");
                    txtAddress.setText("");
                    txtemailId.setText("");
                    txtContactNumber.setText("");

                }
            }
        }

    }//GEN-LAST:event_submitJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thread webcam = new Thread() {

            public void run() {

                opencv_highgui.CvCapture capture = opencv_highgui.cvCreateCameraCapture(0);
                opencv_highgui.cvSetCaptureProperty(capture, opencv_highgui.CV_CAP_PROP_FRAME_HEIGHT, 720);
                opencv_highgui.cvSetCaptureProperty(capture, opencv_highgui.CV_CAP_PROP_FRAME_WIDTH, 720);
                opencv_core.IplImage grabbedImage = opencv_highgui.cvQueryFrame(capture);
                CanvasFrame frame = new CanvasFrame("Webcam");
                while (frame.isVisible() && (grabbedImage = opencv_highgui.cvQueryFrame(capture)) != null) {
                    frame.showImage(grabbedImage);

                }

            }
        };
        webcam.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
        emp = nameJTextField.getText();
        try {
            grabber.start();
            opencv_core.IplImage img = grabber.grab();
            if (img != null) {
                String s = emp + ".jpeg";
                String path = "C:\\Users\\ruchi\\Documents\\NetBeansProjects\\latestnewCompleteProject\\RecieptPdf\\" + s;
                JOptionPane.showMessageDialog(null, "Protograph has been captured as " + s);
                opencv_highgui.cvSaveImage(path, img);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboBoxGender;
    private com.toedter.calendar.JDateChooser dobChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtemailId;
    // End of variables declaration//GEN-END:variables
}
