/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import business.Validation.MyEmailVerifier;
import business.Validation.MyNumericVerifier;
import business.Validation.MyPhoneNumer;
import business.Validation.MyStringVerifier;
import business.Validation.MyaddressVerifier;
import business.Validation.NotEmptyVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruchi
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private ArrayList<String> gen;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.gen = new ArrayList<>();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        MyStringVerifier iv = new MyStringVerifier();
        nameJTextField.setInputVerifier(iv);
        MyaddressVerifier nev = new MyaddressVerifier();
        txtAddress.setInputVerifier(nev);
        MyEmailVerifier nv = new MyEmailVerifier();
        txtemailId.setInputVerifier(nv);
        MyPhoneNumer contact = new MyPhoneNumer();
        txtContactNumber.setInputVerifier(contact);
        NotEmptyVerifier un = new NotEmptyVerifier();
        usernameJTextField.setInputVerifier(un);
        NotEmptyVerifier pass = new NotEmptyVerifier();
        passwordJPasswordField.setInputVerifier(pass);
        NotEmptyVerifier dob = new NotEmptyVerifier();
        dobChooser.setInputVerifier(dob);

        gen.add(new String("MALE"));
        gen.add(new String("FEMALE"));
        gen.add(new String("OTHERS"));
        comboBoxGender.removeAllItems();

        for (String g : gen) {
            comboBoxGender.addItem(g);
        }
        populateTable();
        populateNetworkComboBox();

        txtViewName.setVisible(false);
        txtViewUserName.setVisible(false);
        txtViewAddress.setVisible(false);
        txtViewEmail.setVisible(false);
        txtViewContact.setVisible(false);
        txtViewDob.setVisible(false);
        txtViewGender.setVisible(false);
        txtViewId.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise;
                    row[1] = network.getName();
                    row[2] = userAccount.getUsername();
                    row[3] = enterprise.getEnterpriseType();

                    model.addRow(row);
                }
            }
        }
    }

    private void populateNetworkComboBox() {
        networkJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }
    }

    private void populateEnterpriseComboBox(Network network) {
        enterpriseJComboBox.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseJComboBox.addItem(enterprise);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtemailId = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        usernameJTextField = new javax.swing.JTextField();
        passwordJPasswordField = new javax.swing.JPasswordField();
        dobChooser = new com.toedter.calendar.JDateChooser();
        comboBoxGender = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJComboBox = new javax.swing.JComboBox();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        viewDetailsbtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtViewId = new javax.swing.JTextField();
        txtViewGender = new javax.swing.JTextField();
        txtViewDob = new javax.swing.JTextField();
        txtViewContact = new javax.swing.JTextField();
        txtViewEmail = new javax.swing.JTextField();
        txtViewAddress = new javax.swing.JTextField();
        txtViewUserName = new javax.swing.JTextField();
        txtViewName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 820, -1, -1));

        submitJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 710, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Gender:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Date Of Birth:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Username:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Contact Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Email id:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 180, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 180, -1));

        txtemailId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtemailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 180, -1));

        txtContactNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 180, -1));

        usernameJTextField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 180, -1));

        passwordJPasswordField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(passwordJPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 180, -1));
        add(dobChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 180, -1));

        comboBoxGender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGenderActionPerformed(evt);
            }
        });
        add(comboBoxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 180, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("ENTERPRISE ADMINISTRATOR INFORMATION");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Enterprise:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        enterpriseJComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 180, -1));

        networkJComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 180, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("SELECTION");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        enterpriseJTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Username", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(enterpriseJTable);
        if (enterpriseJTable.getColumnModel().getColumnCount() > 0) {
            enterpriseJTable.getColumnModel().getColumn(0).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(1).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(2).setResizable(false);
            enterpriseJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 650, 95));

        viewDetailsbtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        viewDetailsbtn.setText("View Details");
        viewDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsbtnActionPerformed(evt);
            }
        });
        add(viewDetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        removeBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("ENTERPRISE ADMINISTRATOR DETAILS");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Id:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, -1, -1));

        txtViewId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewId, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, 149, -1));

        txtViewGender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 149, -1));

        txtViewDob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 149, -1));

        txtViewContact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 149, -1));

        txtViewEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 149, -1));

        txtViewAddress.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 149, -1));

        txtViewUserName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 149, -1));

        txtViewName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(txtViewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 149, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Name:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("UserName:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Address:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Email Id:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Contact Number:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Gender:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Date Of Birth:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel23.setText("Click here to view the details");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 220, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel24.setText("Click here to remove the employee created");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 320, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\Final Project\\Project\\src\\userInterface\\Alien Ink 2560X1600 Abstract Background.jpg")); // NOI18N
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1990, 1470));
    }// </editor-fold>//GEN-END:initComponents

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed

        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null) {
            populateEnterpriseComboBox(network);
        }

    }//GEN-LAST:event_networkJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        Network network = (Network) networkJComboBox.getSelectedItem();
        Enterprise enterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();
        String name = nameJTextField.getText();
        String address = txtAddress.getText();
        String emailId = txtemailId.getText();
        String contactNo = txtContactNumber.getText();
        String username = usernameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        Date d2 = dobChooser.getDate();
        String gend = (String) comboBoxGender.getSelectedItem();
        if (dobChooser.getDate() == null||network == null||enterprise==null||name.isEmpty()||address.isEmpty()||emailId.isEmpty()||contactNo.isEmpty()||username.isEmpty()
                ||password.isEmpty()||gend.isEmpty()) {
            if(network == null||enterprise==null||name.isEmpty()||address.isEmpty()||emailId.isEmpty()||contactNo.isEmpty()||username.isEmpty()
                ||password.isEmpty()||gend.isEmpty())
            {
               JOptionPane.showMessageDialog(null, "You cannot leave any field empty"); 
            }
            
            else
            {
                   JOptionPane.showMessageDialog(null, "Please select a date first"); 
                    }
        } else {
            Boolean chk = chkForUnique(username);
            if (chk) {
                Boolean chks = chkAdmin(enterprise);
                if (chks) {
                    Employee employee = enterprise.getEmployeeDirectory().createEmployee(name, address, emailId, contactNo, d2, gend);
                    UserAccount account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new AdminRole());
                    populateTable();
                    nameJTextField.setText("");
                    txtAddress.setText("");
                    txtemailId.setText("");
                    txtContactNumber.setText("");
                    usernameJTextField.setText("");
                    passwordJPasswordField.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Admin for this enterprise has been created");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Please enter another name.This name already exists");
            }
        }

    }//GEN-LAST:event_submitJButtonActionPerformed

    private Boolean chkAdmin(Enterprise en) {
        int flagss = 0;
        for (UserAccount ua : en.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole().equals("Admin Role")) {
                flagss = 1;
            }
        }
        if (flagss == 0) {
            return true;
        } else {
            return false;
        }
    }

    private Boolean chkForUnique(String chkname) {
        int flag = 0;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount u : e.getUserAccountDirectory().getUserAccountList()) {
                    if (u.getUsername().equals(chkname)) {
                        flag = 1;
                    }
                }

            }

        }
        if (flag == 0) {
            return true;
        } else {
            return false;
        }
    }
    private void comboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxGenderActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int row = enterpriseJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Enterprise u = (Enterprise) enterpriseJTable.getValueAt(row, 0);
        for (Network n : system.getNetworkList()) {
            n.getEnterpriseDirectory().removeEnterprise(u);
        }
        populateTable();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void viewDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsbtnActionPerformed
        int row = enterpriseJTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Enterprise u = (Enterprise) enterpriseJTable.getValueAt(row, 0);
        for (UserAccount us : u.getUserAccountDirectory().getUserAccountList()) {
            txtViewName.setText(us.getEmployee().getName());
            txtViewUserName.setText(us.getUsername());
            txtViewAddress.setText(us.getEmployee().getAddress());
            txtViewContact.setText(us.getEmployee().getContactNo());
            Date doBirth = us.getEmployee().getDateOfBirth();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String stringDate = sdf.format(doBirth);
            txtViewDob.setText(stringDate);
            txtViewEmail.setText(us.getEmployee().geteMailId());
            txtViewGender.setText(us.getEmployee().getGender());
            txtViewId.setText(String.valueOf(us.getEmployee().getId()));
            txtViewName.setVisible(true);
            txtViewUserName.setVisible(true);
            txtViewAddress.setVisible(true);
            txtViewEmail.setVisible(true);
            txtViewContact.setVisible(true);
            txtViewDob.setVisible(true);
            txtViewGender.setVisible(true);
            txtViewId.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            jLabel13.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(true);
            jLabel17.setVisible(true);
            jLabel18.setVisible(true);
            txtViewName.setEnabled(false);
            txtViewUserName.setEnabled(false);
            txtViewAddress.setEnabled(false);
            txtViewEmail.setEnabled(false);
            txtViewContact.setEnabled(false);
            txtViewDob.setEnabled(false);
            txtViewGender.setEnabled(false);
            txtViewId.setEnabled(false);
        }

    }//GEN-LAST:event_viewDetailsbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox comboBoxGender;
    private com.toedter.calendar.JDateChooser dobChooser;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTable enterpriseJTable;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtViewAddress;
    private javax.swing.JTextField txtViewContact;
    private javax.swing.JTextField txtViewDob;
    private javax.swing.JTextField txtViewEmail;
    private javax.swing.JTextField txtViewGender;
    private javax.swing.JTextField txtViewId;
    private javax.swing.JTextField txtViewName;
    private javax.swing.JTextField txtViewUserName;
    private javax.swing.JTextField txtemailId;
    private javax.swing.JTextField usernameJTextField;
    private javax.swing.JButton viewDetailsbtn;
    // End of variables declaration//GEN-END:variables
}
