/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SalesPersonRole;

import Business.Enterprise.Enterprise;
import Business.Organization.SalesPersonOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestVitalsWorkRequest;
import Business.WorkQueue.WorkRequest;
import business.Drug.DrugCatalog;
import business.Drug.InitializeDrug;
import java.awt.CardLayout;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

/**
 *
 * @author ruchi
 */
public class SalesPersonWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SalesPersonOrganization sOrganization;
    private Enterprise enterprise;
    private UserAccount userAccount;

    /**
     * Creates new form SalesPersonWorkAreaJPanel
     */
    public SalesPersonWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SalesPersonOrganization organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.sOrganization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        valueLabel1.setText(userAccount.getEmployee().getName());
        viewMedicines.setVisible(false);
        placeAnOrder.setVisible(false);
        populateTable();
        for (WorkRequest request : sOrganization.getWorkQueue().getWorkRequestList()) {
            if (request.getSalesperson() == null) {
                playSound();
            }
        }
    }

    private void playSound() {
        try {

            File file = new File("C:/Users/ruchi/Documents/NetBeansProjects/latestnewCompleteProject/src/userInterface/DeliveryRole/youvegotmail.mp3");
            FileInputStream fis = new FileInputStream(file);
            BufferedInputStream bis = new BufferedInputStream(fis);
            try {
                Player player = new Player(bis);
                player.play();

            } catch (JavaLayerException ex) {

            }

        } catch (IOException e) {
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : sOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getPatientSender().getEmployee().getName();
            row[2] = request.getDoctorSender().getEmployee().getName();
            row[3] = request.getSalesperson() == null ? null : request.getSalesperson().getEmployee().getName();
            row[4] = request.getStatus();
            row[5] = request.getVitalSigns();
            row[6] = request.getVitalSigns().getStatus();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnMedicinesOrderedChk = new javax.swing.JButton();
        placeAnOrder = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        viewMedicines = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ENTERPRISE:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SALES PERSON:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 130, -1));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 215, -1));

        valueLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 215, -1));

        workRequestJTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Patient", "Doctor", "SalesPerson", "Status", "Date on which Vital Sign was recorded", "Body Parameters Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 1127, 97));

        btnMedicinesOrderedChk.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMedicinesOrderedChk.setText("View Medicines Ordered");
        btnMedicinesOrderedChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicinesOrderedChkActionPerformed(evt);
            }
        });
        add(btnMedicinesOrderedChk, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        placeAnOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        placeAnOrder.setText("Place An Order");
        placeAnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeAnOrderActionPerformed(evt);
            }
        });
        add(placeAnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, -1, -1));

        assignBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        assignBtn.setText("Assign To Me");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 220, -1));

        viewMedicines.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        viewMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicinesActionPerformed(evt);
            }
        });
        add(viewMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 740, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ruchi\\Desktop\\Final Project\\Project\\src\\userInterface\\Alien Ink 2560X1600 Abstract Background.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -40, 2390, 1300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicinesOrderedChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicinesOrderedChkActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to view its order");
        } else {
            viewMedicines.setVisible(true);
            placeAnOrder.setVisible(true);
            WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            viewMedicines.setText(request.getMedicines());
        }

    }//GEN-LAST:event_btnMedicinesOrderedChkActionPerformed

    private void placeAnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeAnOrderActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to place an order");
        } else {
            TestVitalsWorkRequest request = (TestVitalsWorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if (request.getSalesperson() != null && !request.getStatus().equals("Request has been sent to the Delivery person.")) {
                request.setStatus("Placing an order for medicines");
                userInterface.SalesPersonRole.PlaceOrderForPatient pofp = new userInterface.SalesPersonRole.PlaceOrderForPatient(userProcessContainer, userAccount, enterprise, request);
                userProcessContainer.add("pofp", pofp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else if (request.getStatus().equals("Request has been sent to the Delivery person.")) {
                JOptionPane.showMessageDialog(null, "This request has already been processed and sent for delivery");
            } else {
                JOptionPane.showMessageDialog(null, "Assign the request first");
            }

        }

    }//GEN-LAST:event_placeAnOrderActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        int selectedRow = workRequestJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "please select a request to be assigned");
        } else {
            WorkRequest request = (WorkRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if (request.getSalesperson() != null) {
                JOptionPane.showMessageDialog(null, "This request has already been assigned to you");
            } else {
                request.setSalesperson(userAccount);
                request.setStatus("Pending with salesperson");
                populateTable();
            }
        }

    }//GEN-LAST:event_assignBtnActionPerformed

    private void viewMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMedicinesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton btnMedicinesOrderedChk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeAnOrder;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JTextField viewMedicines;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
